yii2basic/controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\CommentForm;
use app\models\Article;
use app\models\Tag;
use app\models\ArticleTag;
use app\models\Category;
use yii\data\Pagination;

class SiteController extends Controller
{
    // const PAGE_SIZE = 7;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                // 'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup', 'login', 'index', 'view', 'contact', 'comment', 'tags', 'about'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'index', 'view', 'contact', 'comment', 'tags', 'about'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * @return Response|string
     */
    public function actionIndex($id = null)
    {
        if ($id) {

            //показ статей по категории
            $query = Article::find()->where(['category_id'=> $id]);
            // Для заголовка списка статей определенной категории
            $categoryOne = Category::findOne($id);

        } else {

            //показ статей без категории
            $query = Article::find();
            $categoryOne = null;
            
        }
            $tags = Tag::find()
                ->asArray()
                ->all();;

        //общее количество статей
        $count = $query->count();

        $pagination = new Pagination([
                        'totalCount' => $count, 
                        'pageSize' => 6
                    ]);

        $articles = $query->offset($pagination->offset)
                    ->limit($pagination->limit)
                    ->all();

        // объединяем в один массив
        $result = Article::getSideBar() + compact(
                        'articles', 
                        'pagination',
                        'categoryOne',
                        'tags'
                    );

        return $this->render('index', $result);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionTags($id)
    {
        if ($id) {

            $articleTag = ArticleTag::find()
                    ->with('tag')
                    ->where(['tag_id' => $id])
                    ->asArray()
                    ->all();


            foreach ($articleTag as $v) {
                $articles[] = Article::find()->where(['id'=> $v['article_id']])->one();
            }

            $categoryOne = null;
            $pagination = null;

            $tags = Tag::find()
                ->asArray()
                ->all();;

        // //общее количество статей
        // $count = $query->count();

        // $pagination = new Pagination([
        //                 'totalCount' => $count, 
        //                 'pageSize' => 6
        //             ]);

        // $articles = $query->offset($pagination->offset)
        //             ->limit($pagination->limit)
        //             ->all();

        // объединяем в один массив
        $result = Article::getSideBar() + compact(
                        'articles', 
                        'pagination',
                        'categoryOne',
                        'tags'
                    );

        } 
        return $this->render('index', $result);
    }

    /**
     * Показывает одну статью
     *
     * @return Response|string
     */
    public function actionView($id)
    {
        $article = Article::findOne($id);
        $article->viewedCounter();

        // comments/getComment() - массив объектов Comment
        $comments = $article->getComment()->where(['status' => 1])->all();

        $commentForm = new CommentForm;

        $result = Article::getSideBar() + compact('article', 'comments', 'commentForm');

        return $this->render('single', $result);
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();

        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Сохраняет комментарий в БД
     *
     * @return Response|string
     */
    public function actionComment($id)
    {
        $model = new CommentForm();

        if( Yii::$app->request->isPost ) {

            $model->load( Yii::$app->request->post() );

            if( $model->saveComment($id) ) {

                Yii::$app->getSession()->setFlash('comment', 'Сообщение отправлено.');

            return $this->redirect($_SERVER['HTTP_REFERER']);
            }
        }
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

yii2basic/views/common/header.php
		     <div class="w3_agile_menu">
						   <div class="agileits_w3layouts_nav">
							<div id="toggle_m_nav">
								<div id="m_nav_menu" class="m_nav">
									<div class="m_nav_ham w3_agileits_ham" id="m_ham_1"></div>
									<div class="m_nav_ham" id="m_ham_2"></div>
									<div class="m_nav_ham" id="m_ham_3"></div>
								</div>
							</div>
							<div id="m_nav_container" class="m_nav wthree_bg">
								<nav class="menu menu--sebastian">
									<ul id="m_nav_list" class="m_nav menu__list">
										<li class="m_nav_item active" id="m_nav_item_1"> <a href="index.html" class="link link--kumya"><i class="fa fa-home" aria-hidden="true"></i><span data-letters="Home">Home</span></a></li>
										<li class="m_nav_item" id="moble_nav_item_2"> <a href="typography.html" class="link link--kumya scroll"><i class="fa fa-cog" aria-hidden="true"></i><span data-letters="Services">Services</span></a></li>
										<li class="m_nav_item" id="moble_nav_item_3"> <a href="blog.html" class="link link--kumya scroll"><i class="fa fa-info-circle" aria-hidden="true"></i><span data-letters="Blog">Blog</span></a></li>
										<li class="m_nav_item" id="moble_nav_item_5"> <a href="gallery.html" class="link link--kumya scroll"><i class="fa fa-picture-o" aria-hidden="true"></i><span data-letters="Gallery">Gallery</span></a></li>
										<li class="m_nav_item" id="moble_nav_item_6"> <a href="contact.html" class="link link--kumya scroll"><i class="fa fa-envelope-o" aria-hidden="true"></i><span data-letters="Contact Us">Contact Us</span></a></li>
									</ul>
								</nav>
							</div>
						</div>
                  </div>

yii2basic/views/common/sidebar.php
      <div class="col-md-4 blog-top-right-grid">
        <div class="categories">
          <h3 class="wow fadeInLeft animated animated" data-wow-delay=".5s">Категории</h3>
          <ul>

            <?php foreach($categories as $category): ?>

              <li class="wow fadeInLeft animated animated" data-wow-delay=".5s">
              <a href="<?= Url::toRoute(['site/category', 'id' => $category->id]) ?>"><?= $category->title ?></a>
                <span class="post-count pull-right">(<?= $category->getArticles()->count() ?>)</span>
              </li>

            <?php endforeach; ?>

          </ul>
        </div>
        <div class="categories">
          <h3 class="wow fadeInLeft animated animated" data-wow-delay=".5s">Архив</h3>
          <ul class="marked-list offs1">
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">May 2016 (7)</a></li>
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">April 2016 (11)</a></li>
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">March 2016 (12)</a></li>
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">February 2016 (14)</a> </li>
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">January 2016 (10)</a></li>    
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">December 2014 (12)</a></li>
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">November 2014 (8)</a></li>
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">October 2014 (7)</a> </li>
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">September 2014 (8)</a></li>
            <li class="wow fadeInLeft animated animated" data-wow-delay=".5s"><a href="#">August 2014 (6)</a></li>                          
          </ul>
        </div>
        <div class="comments">
          <h3 class="wow fadeInLeft animated animated" data-wow-delay=".5s">Популярные статьи</h3>

          <?php foreach($popular as $article): ?>

            <div class="comments-text wow fadeInLeft animated animated" data-wow-delay=".5s">
              <div class="col-md-3 comments-left">
                <a href="<?= Url::toRoute(['site/view', 'id' => $article->id]) ?>">
                  <img src="<?= (new Article)->getImage($article->image); ?>" alt="image" />
                </a>
              </div>
              <div class="col-md-9 comments-right">
                <a href="<?= Url::toRoute(['site/view', 'id' => $article->id]) ?>"><?= $article->title ?></a> 
                <p><?= (new Article)->getDate($article->date) ?></p>
              </div>
              <div class="clearfix"> </div>
            </div>

          <?php endforeach; ?>

        </div>
        <div class="comments">
          <h3 class="wow fadeInLeft animated animated" data-wow-delay=".5s">Последние статьи</h3>

          <?php foreach($recent as $article): ?>

            <div class="comments-text wow fadeInLeft animated animated" data-wow-delay=".5s">
              <div class="col-md-3 comments-left">
                <a href="<?= Url::toRoute(['site/view', 'id' => $article->id]) ?>">
                  <img src="<?= (new Article)->getImage($article->image); ?>" alt="image" />
                </a>
              </div>
              <div class="col-md-9 comments-right">
                <a href="<?= Url::toRoute(['site/view', 'id' => $article->id]) ?>"><?= $article->title ?></a> 
                <p><?= (new Article)->getDate($article->date) ?></p>
              </div>
              <div class="clearfix"> </div>
            </div>

          <?php endforeach; ?>

        </div>
      </div>
      
      <div class="clearfix"> </div>
    </div>
  </div>
  <!-- //container -->
</div>
<!-- //blog -->
<!--//end-inner-content-->